//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admin
    {
        public Admin()
        {
            this.Yasaklilars = new HashSet<Yasaklilar>();
        }
    
        public int adminID { get; set; }
        public string adminKullaniciAdi { get; set; }
        public string adminParola { get; set; }
        public string adminYetki { get; set; }
        public string adminMail { get; set; }
    
        public virtual ICollection<Yasaklilar> Yasaklilars { get; set; }
    }
}
