//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bildirimler
    {
        public int bildirimID { get; set; }
        public Nullable<int> kullaniciID { get; set; }
        public string bildirimAciklama { get; set; }
        public Nullable<System.DateTime> bildirimZaman { get; set; }
        public Nullable<bool> bildirimOkunma { get; set; }
        public string bildirimUrl { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
