//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolum
    {
        public Bolum()
        {
            this.Etkinliks = new HashSet<Etkinlik>();
            this.OkunanBolums = new HashSet<OkunanBolum>();
        }
    
        public int bolumID { get; set; }
        public string bolumAd { get; set; }
        public Nullable<int> okulID { get; set; }
    
        public virtual OkulFakulte OkulFakulte { get; set; }
        public virtual ICollection<Etkinlik> Etkinliks { get; set; }
        public virtual ICollection<OkunanBolum> OkunanBolums { get; set; }
    }
}
