//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departman
    {
        public Departman()
        {
            this.Isilanlaris = new HashSet<Isilanlari>();
            this.KullaniciIsGecmisis = new HashSet<KullaniciIsGecmisi>();
        }
    
        public int departmanID { get; set; }
        public string departmanAd { get; set; }
        public Nullable<int> IsyeriID { get; set; }
    
        public virtual ICollection<Isilanlari> Isilanlaris { get; set; }
        public virtual ICollection<KullaniciIsGecmisi> KullaniciIsGecmisis { get; set; }
        public virtual Isyeri Isyeri { get; set; }
    }
}
