//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Etkinlik
    {
        public Etkinlik()
        {
            this.Referans = new HashSet<Referan>();
        }
    
        public int etkinlikID { get; set; }
        public Nullable<int> uniID { get; set; }
        public Nullable<int> okulID { get; set; }
        public Nullable<int> bolumID { get; set; }
        public string icerik { get; set; }
        public Nullable<System.DateTime> etkinlikTarihiBaslangıc { get; set; }
        public Nullable<System.DateTime> etkinlikTarihiBitis { get; set; }
        public Nullable<int> kullaniciOlusturan { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual OkulFakulte OkulFakulte { get; set; }
        public virtual Universite Universite { get; set; }
        public virtual ICollection<Referan> Referans { get; set; }
    }
}
