//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Isilanlari
    {
        public int ilanID { get; set; }
        public Nullable<int> isyeriID { get; set; }
        public Nullable<int> departmanID { get; set; }
        public string acıklama { get; set; }
        public string ücret { get; set; }
    
        public virtual Departman Departman { get; set; }
        public virtual Isyeri Isyeri { get; set; }
    }
}
