//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public Kullanici()
        {
            this.Arkadas = new HashSet<Arkada>();
            this.Arkadas1 = new HashSet<Arkada>();
            this.Bildirimlers = new HashSet<Bildirimler>();
            this.Engellilers = new HashSet<Engelliler>();
            this.Engellilers1 = new HashSet<Engelliler>();
            this.Etkinliks = new HashSet<Etkinlik>();
            this.KullaniciIsGecmisis = new HashSet<KullaniciIsGecmisi>();
            this.Mesajs = new HashSet<Mesaj>();
            this.Mesajs1 = new HashSet<Mesaj>();
            this.OkunanBolums = new HashSet<OkunanBolum>();
            this.Referans = new HashSet<Referan>();
            this.Yasaklilars = new HashSet<Yasaklilar>();
            this.Paylasims = new HashSet<Paylasim>();
            this.Yorums = new HashSet<Yorum>();
        }
    
        public int kullaniciID { get; set; }
        public string isim { get; set; }
        public string soyad { get; set; }
        public string sifre { get; set; }
        public string email { get; set; }
        public Nullable<System.DateTime> dTarihi { get; set; }
        public string hakkimda { get; set; }
        public Nullable<int> sehirID { get; set; }
        public Nullable<bool> aktifmi { get; set; }
        public byte[] resim { get; set; }
        public Nullable<bool> onay { get; set; }
        public Nullable<System.DateTime> uyeKoduZaman { get; set; }
        public string uyeKodu { get; set; }
        public string cinsiyet { get; set; }
        public string isBilgisi { get; set; }
        public string gosterilenMail { get; set; }
        public string facebookURL { get; set; }
        public string twitterURL { get; set; }
    
        public virtual ICollection<Arkada> Arkadas { get; set; }
        public virtual ICollection<Arkada> Arkadas1 { get; set; }
        public virtual ICollection<Bildirimler> Bildirimlers { get; set; }
        public virtual ICollection<Engelliler> Engellilers { get; set; }
        public virtual ICollection<Engelliler> Engellilers1 { get; set; }
        public virtual ICollection<Etkinlik> Etkinliks { get; set; }
        public virtual Sehir Sehir { get; set; }
        public virtual ICollection<KullaniciIsGecmisi> KullaniciIsGecmisis { get; set; }
        public virtual ICollection<Mesaj> Mesajs { get; set; }
        public virtual ICollection<Mesaj> Mesajs1 { get; set; }
        public virtual ICollection<OkunanBolum> OkunanBolums { get; set; }
        public virtual ICollection<Referan> Referans { get; set; }
        public virtual ICollection<Yasaklilar> Yasaklilars { get; set; }
        public virtual ICollection<Paylasim> Paylasims { get; set; }
        public virtual ICollection<Yorum> Yorums { get; set; }
    }
}
