//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciIsGecmisi
    {
        public int isID { get; set; }
        public Nullable<int> kullaniciID { get; set; }
        public Nullable<System.DateTime> isGirisTarihi { get; set; }
        public Nullable<System.DateTime> isCikisTarihi { get; set; }
        public Nullable<int> IsyeriID { get; set; }
        public Nullable<int> departmanID { get; set; }
        public string pozisyon { get; set; }
    
        public virtual Departman Departman { get; set; }
        public virtual Isyeri Isyeri { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
