//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mesaj
    {
        public int mesajID { get; set; }
        public Nullable<int> kullaniciIDGonderen { get; set; }
        public Nullable<int> kullaniciIDAlan { get; set; }
        public string mesajIcerik { get; set; }
        public Nullable<System.DateTime> mesajZaman { get; set; }
        public Nullable<bool> mesajOkunma { get; set; }
        public string mesajGrup { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Kullanici Kullanici1 { get; set; }
    }
}
