//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MezunVsEntities : DbContext
    {
        public MezunVsEntities()
            : base("name=MezunVsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Arkada> Arkadas { get; set; }
        public virtual DbSet<Bildirimler> Bildirimlers { get; set; }
        public virtual DbSet<Bolum> Bolums { get; set; }
        public virtual DbSet<Departman> Departmen { get; set; }
        public virtual DbSet<Engelliler> Engellilers { get; set; }
        public virtual DbSet<Etkinlik> Etkinliks { get; set; }
        public virtual DbSet<Isilanlari> Isilanlaris { get; set; }
        public virtual DbSet<Isyeri> Isyeris { get; set; }
        public virtual DbSet<Kullanici> Kullanicis { get; set; }
        public virtual DbSet<KullaniciIsGecmisi> KullaniciIsGecmisis { get; set; }
        public virtual DbSet<Mesaj> Mesajs { get; set; }
        public virtual DbSet<OkulFakulte> OkulFakultes { get; set; }
        public virtual DbSet<OkunanBolum> OkunanBolums { get; set; }
        public virtual DbSet<Referan> Referans { get; set; }
        public virtual DbSet<Sehir> Sehirs { get; set; }
        public virtual DbSet<Sektor> Sektors { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Universite> Universites { get; set; }
        public virtual DbSet<Yasaklilar> Yasaklilars { get; set; }
        public virtual DbSet<ViewOkul> ViewOkuls { get; set; }
        public virtual DbSet<ViewisBilgisi> ViewisBilgisis { get; set; }
        public virtual DbSet<View_1> View_1 { get; set; }
        public virtual DbSet<ViewMesaj> ViewMesajs { get; set; }
        public virtual DbSet<Paylasim> Paylasims { get; set; }
        public virtual DbSet<Yorum> Yorums { get; set; }
    }
}
