//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OkulFakulte
    {
        public OkulFakulte()
        {
            this.Bolums = new HashSet<Bolum>();
            this.Etkinliks = new HashSet<Etkinlik>();
        }
    
        public int okulID { get; set; }
        public string okulAd { get; set; }
        public Nullable<int> uniID { get; set; }
    
        public virtual ICollection<Bolum> Bolums { get; set; }
        public virtual ICollection<Etkinlik> Etkinliks { get; set; }
        public virtual Universite Universite { get; set; }
    }
}
