//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OkunanBolum
    {
        public int okunanBolumID { get; set; }
        public Nullable<int> kullaniciID { get; set; }
        public Nullable<int> bolumID { get; set; }
        public Nullable<System.DateTime> girisTarihi { get; set; }
        public Nullable<System.DateTime> cikisTarihi { get; set; }
        public Nullable<bool> mezunDurumu { get; set; }
    
        public virtual Bolum Bolum { get; set; }
        public virtual Kullanici Kullanici { get; set; }
    }
}
