//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paylasim
    {
        public Paylasim()
        {
            this.Yorums = new HashSet<Yorum>();
        }
    
        public int paylasimID { get; set; }
        public string grup { get; set; }
        public Nullable<int> ogeID { get; set; }
        public Nullable<int> kullaniciID { get; set; }
        public string icerik { get; set; }
        public Nullable<System.DateTime> tarih { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual ICollection<Yorum> Yorums { get; set; }
    }
}
