//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sehir
    {
        public Sehir()
        {
            this.Isyeris = new HashSet<Isyeri>();
            this.Kullanicis = new HashSet<Kullanici>();
            this.Universites = new HashSet<Universite>();
        }
    
        public int sehirID { get; set; }
        public string sehirAd { get; set; }
    
        public virtual ICollection<Isyeri> Isyeris { get; set; }
        public virtual ICollection<Kullanici> Kullanicis { get; set; }
        public virtual ICollection<Universite> Universites { get; set; }
    }
}
