//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Universite
    {
        public Universite()
        {
            this.Etkinliks = new HashSet<Etkinlik>();
            this.OkulFakultes = new HashSet<OkulFakulte>();
        }
    
        public int uniID { get; set; }
        public string uniAd { get; set; }
        public Nullable<int> sehirID { get; set; }
    
        public virtual ICollection<Etkinlik> Etkinliks { get; set; }
        public virtual ICollection<OkulFakulte> OkulFakultes { get; set; }
        public virtual Sehir Sehir { get; set; }
    }
}
