//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewisBilgisi
    {
        public int isID { get; set; }
        public Nullable<int> departmanID { get; set; }
        public string departmanAd { get; set; }
        public Nullable<int> IsyeriID { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public string IsyeriAd { get; set; }
        public string IsyeriAdres { get; set; }
        public string IsyeriTell { get; set; }
        public Nullable<int> sehırID { get; set; }
        public Nullable<int> sektorID { get; set; }
        public string website { get; set; }
        public string sehirAd { get; set; }
        public string SektorAd { get; set; }
        public string pozisyon { get; set; }
        public Nullable<System.DateTime> isGirisTarihi { get; set; }
        public Nullable<System.DateTime> isCikisTarihi { get; set; }
        public Nullable<int> kullaniciID { get; set; }
    }
}
