//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOkul
    {
        public int okunanBolumID { get; set; }
        public string bolumAd { get; set; }
        public Nullable<int> okulID { get; set; }
        public string okulAd { get; set; }
        public Nullable<int> uniID { get; set; }
        public string uniAd { get; set; }
        public Nullable<int> sehirID { get; set; }
        public string sehirAd { get; set; }
        public Nullable<int> kullaniciID { get; set; }
        public Nullable<System.DateTime> girisTarihi { get; set; }
        public Nullable<System.DateTime> cikisTarihi { get; set; }
    }
}
