//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MezunSistemiProjesi.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMesaj
    {
        public int mesajID { get; set; }
        public Nullable<int> kullaniciIDGonderen { get; set; }
        public Nullable<int> kullaniciIDAlan { get; set; }
        public string mesajIcerik { get; set; }
        public Nullable<System.DateTime> mesajZaman { get; set; }
        public Nullable<bool> mesajOkunma { get; set; }
        public string isim { get; set; }
        public string soyad { get; set; }
        public byte[] resim { get; set; }
    }
}
